<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-wrapper">
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header text-white d-print-none">
            <div class="row align-items-center">
                <div class="col">
                    <!-- Page pre-title -->
                    <div class="page-pretitle">
                        Home
                    </div>
                    <h2 class="page-title">
                        <?php echo sprintf('Edit Invoice %s', str_pad((string)$id, 4, "0", STR_PAD_LEFT)); ?>
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row row-deck row-cards">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Invoice Details</h3>
                        </div>
                        <div class="container">
                            <?php echo $this->flash->output(); ?>
                            <?php if ($this->flashSession->has('success')) { ?>
                                <?php foreach ($this->flashSession->getMessages('success') as $message) { ?>
                                    <div class="alert alert-success" role="alert">
                                        <div class="text-muted"><?php echo $message;  ?></div>
                                    </div>
                                <?php } ?>
                            <?php } ?>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="<?php echo $id ? 'col-md-3' : 'col-md-6' ?>">
                                    <?php echo $this->getContent(); ?>
                                    <div class="card">
                                        <!-- <div class="card-header">

                                        </div> -->
                                        <div class="card-body">
                                            <form action="<?php printf('/invoice/edit/%s', $invoice->id); ?>" class="form-horizontal" method="post">
                                                <div class="mb-3">
                                                    <label class="form-label required">Invoice Code</label>
                                                    <?php
                                                    echo $this->tag->textField(["invoice_codex", "type" => "text", "value" => str_pad((string)$id, 4, "0", STR_PAD_LEFT), "readOnly" => "readOnly", "class" => "form-control", "id" => "invoiceCode", "placeholder" => "Invoice Code"]);
                                                    ?>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label required">Subject</label>
                                                    <?php echo $this->tag->textField(["subject", "type" => "text", "class" => "form-control", "id" => "invoiceSubject", "placeholder" => "Subject"]); ?>
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label required">Issue Date</label>
                                                    <div class="input-icon">
                                                        <span class="input-icon-addon">
                                                            <!-- Download SVG icon from http://tabler-icons.io/i/calendar -->
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                <rect x="4" y="5" width="16" height="16" rx="2" />
                                                                <line x1="16" y1="3" x2="16" y2="7" />
                                                                <line x1="8" y1="3" x2="8" y2="7" />
                                                                <line x1="4" y1="11" x2="20" y2="11" />
                                                                <line x1="11" y1="15" x2="12" y2="15" />
                                                                <line x1="12" y1="15" x2="12" y2="18" />
                                                            </svg>
                                                        </span>
                                                        <?php echo $this->tag->textField(["issue_date", "type" => "text", "class" => "form-control datepicker", "id" => "issueDate", "placeholder" => "Issue Date", "autocomplete" => "off"]); ?>
                                                    </div>
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label required">Due Date</label>
                                                    <div class="input-icon">
                                                        <span class="input-icon-addon">
                                                            <!-- Download SVG icon from http://tabler-icons.io/i/calendar -->
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                <rect x="4" y="5" width="16" height="16" rx="2" />
                                                                <line x1="16" y1="3" x2="16" y2="7" />
                                                                <line x1="8" y1="3" x2="8" y2="7" />
                                                                <line x1="4" y1="11" x2="20" y2="11" />
                                                                <line x1="11" y1="15" x2="12" y2="15" />
                                                                <line x1="12" y1="15" x2="12" y2="18" />
                                                            </svg>
                                                        </span>
                                                        <?php echo $this->tag->textField(["due_date", "type" => "text", "class" => "form-control datepicker", "id" => "dueDate", "placeholder" => "Due Date", "autocomplete" => "off"]); ?>
                                                    </div>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label required">Issuer</label>
                                                    <?php echo $this->tag->select(["from", $customers, "using" => ["id", "name"], "type" => "number", "class" => "form-control form-select", "id" => "invoiceIssuer", "placeholder" => "Invoice issuer"]); ?>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label required">Client</label>
                                                    <?php echo $this->tag->select(["for", $customers, "using" => ["id", "name"], "type" => "number", "class" => "form-control form-select", "id" => "invoiceClient", "placeholder" => "Invoice client"]); ?>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label">Is Paid?</label>
                                                    <label class="form-check form-switch">
                                                        <?php if ($invoice->is_paid === 'Y') { ?>
                                                            <input class="form-check-input is-paid" checked="checked" type="checkbox">
                                                            <span class="form-check-label is-paid-label">Yes</span>
                                                        <?php } else { ?>
                                                            <input class="form-check-input is-paid" type="checkbox">
                                                            <span class="form-check-label is-paid-label">No</span>
                                                        <?php } ?>
                                                    </label>

                                                    <?php echo $this->tag->hiddenField(["is_paid", "id" => "isPaid", "value" => ($invoice->is_paid === 'Y') ? 'Y' : 'N']); ?>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label">Notes</label>
                                                    <?php echo $this->tag->textArea(["notes", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNotes"]); ?>
                                                </div>

                                                <?php
                                                if ($id) {
                                                    echo $this->tag->hiddenField("id");
                                                }
                                                ?>
                                                <div class="form-group">
                                                    <div class="col-sm-offset-2 col-sm-10">
                                                        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($id) { ?>
                                    <div class="col-md-9">
                                        <div class="col-12">
                                            <div class="card">
                                                <div class="card-header">
                                                    <h3 class="card-title">Invoices Items</h3>
                                                    <div class="col-auto ms-auto d-print-none text-end">
                                                        <div class="btn-list">
                                                            <a href="#" class="btn btn-primary d-none d-sm-inline-block" data-bs-toggle="modal" data-bs-target="#modalInvoiceDetail" aria-label="Add invoice item">
                                                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                    <line x1="12" y1="5" x2="12" y2="19" />
                                                                    <line x1="5" y1="12" x2="19" y2="12" />
                                                                </svg>
                                                                Add item
                                                            </a>
                                                            <a href="#" class="btn btn-primary d-sm-none btn-icon" data-bs-toggle="modal" data-bs-target="#modalInvoiceDetail" aria-label="Add invoice item">
                                                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                    <line x1="12" y1="5" x2="12" y2="19" />
                                                                    <line x1="5" y1="12" x2="19" y2="12" />
                                                                </svg>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="card-body">
                                                    <div class="table-responsive">
                                                        <table class="table card-table table-striped table-vcenter text-nowrap datatable" id="datatable">
                                                            <thead>
                                                                <tr>
                                                                    <th class="w-1">No.
                                                                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-sm text-dark icon-thick" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                            <polyline points="6 15 12 9 18 15" />
                                                                        </svg>
                                                                    </th>
                                                                    <th>Item type</th>
                                                                    <th>Description</th>
                                                                    <th>Quantity</th>
                                                                    <th>Unit Price</th>
                                                                    <th>Amount</th>
                                                                    <th></th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <?php
                                                                $n = 1;
                                                                foreach ($invoice->invoiceDetails as $invoice_item) { ?>
                                                                    <tr>
                                                                        <td><span class="text-muted"><?php echo $n++; ?></span></td>
                                                                        <td><?php echo $invoice_item->products->productTypes->name; ?></td>
                                                                        <td><?php echo $invoice_item->products->name; ?></td>
                                                                        <td><?php echo $invoice_item->quantity; ?></td>
                                                                        <td><?php echo Number::formatRupiah($invoice_item->products->unit_price); ?></td>
                                                                        <td><?php echo Number::formatRupiah($invoice_item->products->unit_price * $invoice_item->quantity); ?></td>
                                                                        <td class="text-end">
                                                                            <span class="dropdown">
                                                                                <button class="btn dropdown-toggle align-text-top" data-bs-boundary="viewport" data-bs-toggle="dropdown">Actions</button>
                                                                                <div class="dropdown-menu dropdown-menu-end">
                                                                                    <a class="dropdown-item invoice-item" data-item-id="<?php echo $invoice_item->id; ?>" data-product-id="<?php echo $invoice_item->product_id; ?>" data-quantity="<?php echo $invoice_item->quantity; ?>" data-notes="<?php echo $invoice_item->notes; ?>" data-bs-toggle="modal" data-bs-target="#modalInvoiceDetail" aria-label="Add invoice item" href="#">
                                                                                        Edit
                                                                                    </a>
                                                                                    <a class="dropdown-item" href="<?php printf('/invoice/edit/%s/%s/delete', $invoice->id, $invoice_item->id); ?>">
                                                                                        Delete
                                                                                    </a>
                                                                                </div>
                                                                            </span>
                                                                        </td>
                                                                    </tr>
                                                                <?php } ?>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                    <!-- </div>
                                                <div class="card-body"> -->
                                                    <div class="text-end">
                                                        <span>Subtotal: <strong><?php echo Number::formatRupiah($invoice::getTotalPrice($invoice)); ?></strong></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php } ?>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal modal-blur fade" id="modalInvoiceDetail" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add item</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="<?php printf('/invoice/edit/%s/%s', $invoice->id, ($latest_invoice_detail->id + 1)); ?>" name="invoiceItemForm" class="form-horizontal" method="post">
                <div class="modal-body">
                    <?php echo $this->getContent(); ?>

                    <div class="mb-3">
                        <label class="form-label required">Invoice Code</label>
                        <?php echo $this->tag->textField(["invoice_codex", "type" => "text", "value" => str_pad((string)$latest_invoice->id, 4, "0", STR_PAD_LEFT), "readOnly" => "readOnly", "class" => "form-control", "id" => "invoiceCode", "placeholder" => "Invoice Code"]); ?>
                        <?php echo $this->tag->hiddenField(["invoice_id", "value" => $id]); ?>
                    </div>
                    <div class="mb-3">
                        <label class="form-label required">Product</label>
                        <?php echo $this->tag->select(["product_id", $products, "using" => ["id", "name"], "type" => "number", "class" => "form-control form-select", "id" => "itemProductId"]); ?>
                    </div>
                    <div class="mb-3">
                        <label class="form-label required">Quantity</label>
                        <?php echo $this->tag->numericField(["quantity", "type" => "number", "value" => "1", "min" => 1, "required" => "required", "class" => "form-control", "id" => "itemQuantity"]); ?>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Notes</label>
                        <?php echo $this->tag->textArea(["notes", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "itemNotes"]); ?>
                    </div>
                </div>
                <?php echo $this->tag->hiddenField(["item_id", value => "", "id" => "itemId"]); ?> 

                <div class="modal-footer">
                    <a href="#" class="btn btn-link link-secondary" data-bs-dismiss="modal">
                        Cancel
                    </a>
                    <a href="#" class="btn btn-primary ms-auto submit-form">
                        Submit
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

<?php

$js = '
    $(document).ready( function () {
        $("#datatable").DataTable();
    } );
';
$css = '
.table>:not(caption)>*>* {
    border-bottom-width: 0;
}
';
$this
    ->assets
    ->addInlineCss($css)
    ->addInlineJs($js);
?>