<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-wrapper">
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header text-white d-print-none">
            <div class="row align-items-center">
                <div class="col">
                    <!-- Page pre-title -->
                    <div class="page-pretitle">
                        Home
                    </div>
                    <h2 class="page-title">
                        New Invoice
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row row-deck row-cards">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Invoice Details</h3>
                        </div>
                        <div class="container">
                            <?php echo $this->flash->output(); ?>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="<?php echo $id ? 'col-md-3' : 'col-md-6' ?>">
                                    <?php echo $this->getContent(); ?>
                                    <div class="card">
                                        <div class="card-body">
                                            <form action="/invoice/new" class="form-horizontal" method="post">
                                                <div class="mb-3">
                                                    <label class="form-label required">Invoice Code</label>
                                                    <?php
                                                    echo $this->tag->textField(["invoice_code_display", "type" => "text", "value" => str_pad((string)($latest_invoice->id + 1), 4, "0", STR_PAD_LEFT), "readOnly" => "readOnly", "class" => "form-control", "id" => "invoiceCode", "placeholder" => "Invoice Code"]);
                                                    echo $this->tag->hiddenField(["invoice_code", "type" => "hidden", "value" => ($latest_invoice->id + 1), "class" => "form-control", "id" => "fieldInvoiceCode", "placeholder" => "Invoice Code"]);
                                                    ?>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label required">Subject</label>
                                                    <?php echo $this->tag->textField(["subject", "type" => "text", "class" => "form-control", "id" => "invoiceSubject", "placeholder" => "Subject"]); ?>
                                                </div>
                                                <div class="mb-3 col-md-3">
                                                    <label class="form-label required">Issue Date</label>
                                                    <div class="input-icon">
                                                        <span class="input-icon-addon">
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                <rect x="4" y="5" width="16" height="16" rx="2" />
                                                                <line x1="16" y1="3" x2="16" y2="7" />
                                                                <line x1="8" y1="3" x2="8" y2="7" />
                                                                <line x1="4" y1="11" x2="20" y2="11" />
                                                                <line x1="11" y1="15" x2="12" y2="15" />
                                                                <line x1="12" y1="15" x2="12" y2="18" />
                                                            </svg>
                                                        </span>
                                                        <?php echo $this->tag->textField(["issue_date", "type" => "text", "class" => "form-control datepicker", "id" => "issueDate", "placeholder" => "Issue Date", "autocomplete" => "off"]); ?>
                                                    </div>
                                                </div>
                                                <div class="mb-3 col-md-3">
                                                    <label class="form-label required">Due Date</label>
                                                    <div class="input-icon">
                                                        <span class="input-icon-addon">
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                                <rect x="4" y="5" width="16" height="16" rx="2" />
                                                                <line x1="16" y1="3" x2="16" y2="7" />
                                                                <line x1="8" y1="3" x2="8" y2="7" />
                                                                <line x1="4" y1="11" x2="20" y2="11" />
                                                                <line x1="11" y1="15" x2="12" y2="15" />
                                                                <line x1="12" y1="15" x2="12" y2="18" />
                                                            </svg>
                                                        </span>
                                                        <?php echo $this->tag->textField(["due_date", "type" => "text", "class" => "form-control datepicker", "id" => "dueDate", "placeholder" => "Due Date", "autocomplete" => "off"]); ?>
                                                    </div>
                                                </div>
                                                <div class="mb-3 col-md-5">
                                                    <label class="form-label required">Issuer</label>
                                                    <?php echo $this->tag->select(["from", $customers, "using" => ["id", "name"], "type" => "number", "class" => "form-control form-select", "id" => "invoiceIssuer", "placeholder" => "Invoice issuer"]); ?>
                                                </div>
                                                <div class="mb-3 col-md-5">
                                                    <label class="form-label required">Client</label>
                                                    <?php echo $this->tag->select(["for", $customers, "using" => ["id", "name"], "type" => "number", "class" => "form-control form-select", "id" => "invoiceClient", "placeholder" => "Invoice client"]); ?>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label">Is Paid?</label>
                                                    <label class="form-check form-switch">
                                                        <input class="form-check-input is-paid" type="checkbox">
                                                        <span class="form-check-label is-paid-label">No</span>
                                                    </label>

                                                    <?php echo $this->tag->hiddenField(["is_paid", "id" => "isPaid", "value" => "N"]); ?>
                                                </div>
                                                <div class="mb-3">
                                                    <label class="form-label">Notes</label>
                                                    <?php echo $this->tag->textArea(["notes", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNotes"]); ?>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-sm-offset-2 col-sm-10">
                                                        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>