<div class="page-wrapper">
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header text-white d-print-none">
            <div class="row align-items-center">
                <div class="col">
                    <h2 class="page-title">
                        Invoice
                    </h2>
                </div>
                <!-- Page title actions -->
                <div class="col-auto ms-auto d-print-none">
                    <button type="button" class="btn btn-primary" id="getPdf">
                        <!-- Download SVG icon from http://tabler-icons.io/i/printer -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M17 17h2a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-14a2 2 0 0 0 -2 2v4a2 2 0 0 0 2 2h2" />
                            <path d="M17 9v-4a2 2 0 0 0 -2 -2h-6a2 2 0 0 0 -2 2v4" />
                            <rect x="7" y="13" width="10" height="8" rx="2" />
                        </svg>
                        Get Pdf
                    </button>
                    <button type="button" class="btn btn-primary" onclick="javascript:window.print();">
                        <!-- Download SVG icon from http://tabler-icons.io/i/printer -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M17 17h2a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-14a2 2 0 0 0 -2 2v4a2 2 0 0 0 2 2h2" />
                            <path d="M17 9v-4a2 2 0 0 0 -2 -2h-6a2 2 0 0 0 -2 2v4" />
                            <rect x="7" y="13" width="10" height="8" rx="2" />
                        </svg>
                        Print Invoice
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="card card-lg">
                <div id="print-area">
                    <div class="card-body">
                        <div class="row mb-4">
                            <div class="col-9">
                                <p class="h1 mb-5">INVOICE</p>
                                <div class="row">
                                    <div class="row">
                                        <div class="col-2 mb-2 invoice-label">Invoice ID</div>
                                        <div class="col-10 invoice-value"><?php echo str_pad((string)$invoice->id, 4, "0", STR_PAD_LEFT); ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-2 mb-2 invoice-label">Issue Date</div>
                                        <div class="col-10 invoice-value"><?php echo date('d/m/Y', strtotime($invoice->issue_date)); ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-2 mb-2 invoice-label">Due Date</div>
                                        <div class="col-10 invoice-value"><?php echo date('d/m/Y', strtotime($invoice->due_date)); ?></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-2 mb-2 invoice-label">Subject</div>
                                        <div class="col-10 invoice-value"><?php echo $invoice->subject; ?></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="row mb-3">
                                    <div class="col-3 mb-2 invoice-label">From</div>
                                    <div class="col-9 mb-2 invoice-value">
                                        <h3><?php echo $invoice->CustomerFrom->name; ?></h3>
                                        <span><?php echo $invoice->CustomerFrom->address; ?></span>
                                        <span><?php printf('%s %s', $invoice->CustomerFrom->city, $invoice->CustomerFrom->postcode); ?></span>
                                        <br />
                                        <span><?php echo Countries::getCountryByCode($invoice->CustomerFrom->country_code); ?></span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-3 mb-2 invoice-label">To</div>
                                    <div class="col-9 mb-2 invoice-value">
                                        <h3><?php echo $invoice->CustomerFor->name; ?></h3>
                                        <span><?php echo $invoice->CustomerFor->address; ?></span>
                                        <span><?php printf('%s %s', $invoice->CustomerFor->city, $invoice->CustomerFor->postcode); ?></span>
                                        <br />
                                        <span><?php echo Countries::getCountryByCode($invoice->CustomerFor->country_code); ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <table class="table table-transparent table-responsive">
                                <thead>
                                    <tr>
                                        <th>Item Type</th>
                                        <th>Description</th>
                                        <th class="text-end" style="width: 1%">Quantity</th>
                                        <th class="text-end" style="width: 1%">Unit Price</th>
                                        <th class="text-end" style="width: 1%">Amount</th>
                                    </tr>
                                </thead>
                                <?php foreach ($invoice->invoiceDetails as $invoice_item) { ?>
                                    <tr>
                                        <td>
                                            <div class="text-muted"><?php echo $invoice_item->products->productTypes->name; ?></div>
                                        </td>
                                        <td>
                                            <div class="text-muted"><?php echo $invoice_item->products->name; ?></div>
                                        </td>
                                        <td class="text-end"><?php echo $invoice_item->quantity; ?></td>
                                        <td class="text-end"><?php echo Number::formatRupiah($invoice_item->products->unit_price); ?></td>
                                        <td class="text-end strong"><?php echo Number::formatRupiah($invoice_item->products->unit_price * $invoice_item->quantity); ?></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>
                        <div class="row text-end">
                            <div class="col-4 offset-8">
                                <div class="row">
                                    <div class="col-6 mb-2 invoice-label">Subtotal</div>
                                    <div class="col-6 strong"><?php echo Number::formatRupiah($invoice::getTotalPrice($invoice)); ?></div>
                                </div>
                                <div class="row">
                                    <div class="col-6 mb-2 invoice-label">Tax (10%)</div>
                                    <div class="col-6 strong"><?php echo Number::formatRupiah($invoice::getTotalPriceWithTax($invoice, 10)); ?></div>
                                </div>
                                <div class="row">
                                    <div class="col-6 mb-2 invoice-label">Payments</div>
                                    <div class="col-6 strong"><?php echo $invoice->is_paid === 'Y' ? sprintf('-%s', Number::formatRupiah($invoice::getTotalPrice($invoice))) : Number::formatRupiah(0); ?></div>
                                </div>
                                <div class="row">
                                    <div class="col-6 mb-2">
                                        <h3>Ammount due</h3>
                                    </div>
                                    <div class="col-6 strong"><?php echo $invoice->is_paid === 'Y' ? Number::formatRupiah(0) : sprintf('%s', Number::formatRupiah($invoice::getTotalPrice($invoice))); ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>